apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
  labels:
    owner: zxc
    env: demo
spec:
  containers:
    - image: busybox:latest
      name: busy
      # 拉取策略 
      imagePullPolicy: IfNotPresent
      env: 
        - name: os
          value: "windows"
        - name : debug
          value: "no"
      command:
        - /bin/bash
      args:
        - "$(os),$(debug)"